"""create leads table

Revision ID: 2cb455e93ac7
Revises: 
Create Date: 2026-09-17 09:58:23.886026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb455e93ac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('raw_enquiry', sa.Text(), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('intent', sa.Enum('buy', 'rent', 'sell', 'land', name='lead_intent'), nullable=True),
    sa.Column('timeline', sa.String(length=100), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('lead_category', sa.Enum('HOT', 'WARM', 'COLD', name='lead_category'), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('human_agent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bedrooms IS NULL OR bedrooms > 0', name='ck_leads_bedrooms_positive'),
    sa.CheckConstraint('budget IS NULL OR budget >= 0', name='ck_leads_budget_non_negative'),
    sa.CheckConstraint('lead_score >= 0 AND lead_score <= 100', name='ck_leads_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_lead_category'), 'leads', ['lead_category'], unique=False)
    op.create_index(op.f('ix_leads_location'), 'leads', ['location'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_processing_status'), 'leads', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_processing_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_location'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_category'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
